
/**
 * Create Elements
 */

const contentDiv = document.createElement("div")

// Header
const header = document.createElement("h4")
header.setAttribute("class", "my-5")
header.innerText = "Single Page Application"

// Nav & Links
const nav = document.createElement("ul")
nav.setAttribute("class", "nav justify-content-center")

const links = [
    {
        href: "#",
        text: "Home"
    },
    {
        href: "#page1",
        text: "Page 1"
    },
    {
        href: "#page2",
        text: "Page 2"
    }
]

for (let link of links) {
    const li = document.createElement("li")
    li.setAttribute("class", "nav-item")
    const a = document.createElement("a")
    a.setAttribute("class", "nav-link")
    a.setAttribute("href", link.href)
    a.innerText = link.text

    li.appendChild(a)

    nav.appendChild(li)
}

// Content Card
const contentCard = document.createElement("div")
contentCard.setAttribute("class", "card my-5 bg-light")

const contentCardBody = document.createElement("div")
contentCardBody.setAttribute("class", "card-body")

const contentCardTitle = document.createElement("h5")
contentCardTitle.setAttribute("class", "card-title")
contentCardTitle.innerText = "Home"

const contentCardText = document.createElement("card-text")
contentCardText.setAttribute("class", "card-text")
contentCardText.innerText = "Welcome to the home page."

contentCardBody.appendChild(contentCardTitle)
contentCardBody.appendChild(contentCardText)
contentCard.appendChild(contentCardBody)

/**
 * Append elements to body
 */
contentDiv.setAttribute("class", "container text-center")
contentDiv.appendChild(header)
contentDiv.appendChild(nav)
contentDiv.appendChild(contentCard)


document.body.appendChild(contentDiv)

/**
 * Content switching
 */

const contentData = {
    "": {
        title: "Home",
        text: "Welcome to the home page."
    },
    "#page1": {
        title: "Page 1",
        text: "Welcome to page 1. This is content that is generated by Javascript."
    },
    "#page2": {
        title: "Page 2",
        text: "Welcome to page 2. This is content that is generated by Javascript as well."
    }
}

// Update shown content
function loadPage() {
    const {hash} = location
    const {title, text} = contentData[hash]

    contentCardTitle.innerText = title
    contentCardText.innerText = text
}

// Add event listeners
addEventListener("hashchange", loadPage)
addEventListener("load", loadPage)